### ISSUE TITLE
why package-lock.json is in gitignore ?

### ISSUE THREAD

**Issue by tsamaya** [boly38/node-mongotools#13]
Hello @Boly38,

npm documentation recommend storing this file in source control https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json

Here I can see it is not the case and the file is part of the `.gitignore` file. 

Any reason?

**Comment by boly38** [comment]
hi @tsamaya 👋
it's an issue
feel free to post a pr or else I'll do that asap

**Comment by boly38** [comment]
fixed in **1.0.2**

**Comment by tsamaya** [comment]
Well done 👍
