### ISSUE TITLE
Cannot set --sslCAFile (or tlsCAFile) option

### ISSUE THREAD

**Issue by hongline3** [boly38/node-mongotools#44]
I tried to using this library.
In my case, I use self-signed CA file for my MongoDB Cluster, so need to specify CA certificated I had created. But this library doesn't seem to be support --sslCAFile option which supported at mongodump. (Both mongodump and mongorestore)

Hope support --sslCAFile options.

**Comment by boly38** [comment]
welcome and thanks @hongline3 for this issue, I will try to add it

**Comment by boly38** [comment]
fixed in `2.0.0`, [hongline3](https://github.com/hongline3) don't hesitate to provide a feedback here and re-open if needed.
