### ISSUE TITLE
Question - can we select all databases in URI for mongodump?

### ISSUE THREAD

**Issue by jatinkumarg** [boly38/node-mongotools#47]
I was wondering how can we select all databases in URI for `mongodump` operation? Is there any option available that I can pass to trigger select all databases for mongodump while using URI for connection?

**Comment by boly38** [comment]
Welcome @jatinkumarg and thanks for your question 🤝 

I have made a local test using an uri without database like this :

```bash
export MT_MONGO_URI=mongodb://127.0.0.1:27017
# node mt options
node mt dump
```

NB: I added a new `mt options` command to show current options values to help usage. I will push that ASAP.

In the [wrapper code](https://github.com/boly38/node-mongotools/blob/main/lib/MTWrapper.js#L8L24)
- `options.uri` is first arg checked and has the precedence prior to `options.db`

My dump using `uri` without db (like `mongodb://127.0.0.1:27017`) takes all databases from `127.0.0.1:27017`.

So I think without update it's already ok to dump all databases.

Note that in general, the wrapper here represents the official `mongodump` binary options. Having a look into mongo [mongodump documentation](https://www.mongodb.com/docs/database-tools/mongodump/#syntax), the sample provided doesn't includes databasename but in addition the [uri connection string](https://www.mongodb.com/docs/database-tools/mongodump/#std-option-mongodump.--uri) permits that. So you have the choice: no db name means "all", or one db name means "dump only this one".

Let me know if I answer to your question, then we could close this issue.

**Comment by jatinkumarg** [comment]
I'm using one of the Atlas clusters to connect with and the only way I connect to the Atlas cluster is by using URI. Apparently, whenever I use URI with node-mongotools I have to pass in the database name as a requirement other wise I just get an empty dump file. I was wondering if there is any option I can pass to override the selective database thing so I can just dump all the database at once using URI approach?

**Comment by jatinkumarg** [comment]
I get this error whenever I leave the database name empty in URI

```error: 'INVALID_OPTIONS', message: 'database name for dump is required.'```

Why is database name required in URI? By default, `mongodump` does not require a database name so was wondering if we can remove this condition or add another condition not override the database name requirement for URI.

**Comment by boly38** [comment]
that's a good point :) I'll need to fix that !

NB:dbname is used to build default output dump filename, need a replacement if empty

**Comment by jatinkumarg** [comment]
ahh makes sense. If possible can we have another default dump filename in case there is no database name given? Maybe we can call it something like `*` or `all`, whichever keywords work well.

**Comment by boly38** [comment]
@jatinkumarg please update to `2.0.1` and try again to dump using uri (without db name); it should work. 
Thanks ! If needed re-open this issue.
