### ISSUE TITLE
Example sample_backup_and_rotate.js not working on version v2.1.0

### ISSUE THREAD

**Issue by freakinside** [boly38/node-mongotools#57]
Problem with require and import.

Downgraded to latest v1 and it works.

**Comment by boly38** [comment]
hi @freakinside thanks for your report, I will look at this asap 👍  sorry for the inconvenience

**Comment by boly38** [comment]
2.1.1 is [on the way](https://github.com/boly38/node-mongotools/actions)

**Comment by freakinside** [comment]
It works.

Finally i was not able to dump from one db and restore in a different one but thats not a bug.

Thanks a lot.
