### ISSUE TITLE
I cannot restore a previously dumped database.

### ISSUE THREAD

**Issue by dandziz** [boly38/node-mongotools#76]
```import path from "path";
import { MongoTools, MTOptions, MTCommand } from "node-mongotools";

var mongoTools = new MongoTools();
const mtOptions = {
  db: 'tobaco-images',
  dumpFile: path.join(
    "config/mongodb/backups/tobaco-images__2023-11-26_114853.gz"
  ),
};

mongoTools.mongorestore(mtOptions)
  .then((result) => {
    console.log(result);
  })
  .catch((error) => {
    console.log(error);
  });
```
I did a dump of a database and then I tried to restore from that dumped file but nothing changed in my database. Which step did I do wrong? Thanks for all the help from everyone.

```
import path from 'path'
import { MongoTools, MTOptions, MTCommand } from "node-mongotools";

var mongoTools = new MongoTools();
const mtOptions = {
  db: 'tobaco-images',
  port: 27017,
  path: path.join('config/mongodb/backups'),
};

var promiseResult = mongoTools.mongodump(mtOptions);

promiseResult.then((result) => {
  console.log(result);
}).catch((error) => {
  console.log(error)
})
```
![image](https://github.com/boly38/node-mongotools/assets/94340886/8ddcbbba-9e78-4780-b946-0e8532b00637)

**Comment by boly38** [comment]
Hi @dandziz 
Really sorry for the delay, I completely miss that repository issues since a while :/

Did you always get restore issue ? If yes did you get some error output?

In addition and in order to help understanding the issue you can add the option `'showCommand` with `true` as value to get wrapper result full command line to see what's wrong or wrongly wrapped (if for example using mongorestore bin on your own you have a success).

**Comment by hanandika** [comment]
``` 
{
      dumpFile: Helpers.tmpPath('backups')+'/'+fileName,
      host:'1.2.3.4',
      username:'username',
      password:'password',
      db:'*',
      authDb:'admin',
      showCommand: true,
      dropBeforeRestore: true
}
```

These are my options, and successfully restoring small-size DB


```
2024-04-16T16:04:31.170+0700    restoring x?authSource=admin.externaldatas from archive 'x/tmp/backups/x_authSource_admin__2024-04-16_132145.gz'
2024-04-16T16:04:32.291+0700    finished restoring x?authSource=admin.externaldatas (4905 documents, 0 failures)
2024-04-16T16:04:32.291+0700    no indexes to restore for collection x?authSource=admin.artmsanpr
2024-04-16T16:04:32.291+0700    no indexes to restore for collection x?authSource=admin.externaldatas
2024-04-16T16:04:32.291+0700    no indexes to restore for collection x?authSource=admin.tracking
2024-04-16T16:04:32.291+0700    no indexes to restore for collection x?authSource=admin.logs
2024-04-16T16:04:32.292+0700    15322 document(s) restored successfully. 0 document(s) failed to restore.
```

**Comment by boly38** [comment]
After doing some test, it appears that I not completely get your point (but there is not so much context :p) 

If you dump "toto-db" and try to restore "toto-db", this produce a mongorestore successcommand but wich dont restore nothing.
After that if you try to restore wiith db:"*" then you get real restore success. That's strange to me. I'll maybe dig more this usecase to avoid bad user experience like yours! thanks for your contribution.

**Comment by boly38** [comment]
In fact this is a bug
Db is wrapped as nsInclude which is a way to filter "collections namespace"..
I ll provide a fix fot that
